Preserve reqwest error for the releases page
Previously, a github api status error for the github releases page would show a confusing error message in uv:

```
$ uv self update
info: Checking for updates...
error: No releases were found for the app uv in workspace uv
```

Now it should fall into the same custom error path as our offline error handling:

```
$ uv self update
  info: Checking for updates...
  error: Could not connect, are you offline?
    Caused by: error sending request for url (https://api.github.com/repos/astral-sh/uv/releases): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    Caused by: error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    Caused by: dns error: failed to lookup address information: Temporary failure in name resolution
    Caused by: failed to lookup address information: Temporary failure in name resolution
```

I'm not sure how to test this, we'd need to mock github with a custom ssl certificate and everything.